"""NAF/APE code reference table (rev 2 + common codes).

Source: INSEE — Nomenclature d'Activites Francaise rev. 2
Contains all 21 sections + 200+ most common specific codes.
"""

# 21 top-level sections
NAF_SECTIONS: dict[str, str] = {
    "A": "Agriculture, sylviculture et peche",
    "B": "Industries extractives",
    "C": "Industrie manufacturiere",
    "D": "Production et distribution d'electricite, de gaz, de vapeur et d'air conditionne",
    "E": "Production et distribution d'eau; assainissement, gestion des dechets et depollution",
    "F": "Construction",
    "G": "Commerce; reparation d'automobiles et de motocycles",
    "H": "Transports et entreposage",
    "I": "Hebergement et restauration",
    "J": "Information et communication",
    "K": "Activites financieres et d'assurance",
    "L": "Activites immobilieres",
    "M": "Activites specialisees, scientifiques et techniques",
    "N": "Activites de services administratifs et de soutien",
    "O": "Administration publique",
    "P": "Enseignement",
    "Q": "Sante humaine et action sociale",
    "R": "Arts, spectacles et activites recreatives",
    "S": "Autres activites de services",
    "T": "Activites des menages en tant qu'employeurs",
    "U": "Activites extra-territoriales",
}

# Section letter for each 2-digit division
NAF_DIVISION_TO_SECTION: dict[str, str] = {
    "01": "A", "02": "A", "03": "A",
    "05": "B", "06": "B", "07": "B", "08": "B", "09": "B",
    "10": "C", "11": "C", "12": "C", "13": "C", "14": "C", "15": "C", "16": "C",
    "17": "C", "18": "C", "19": "C", "20": "C", "21": "C", "22": "C", "23": "C",
    "24": "C", "25": "C", "26": "C", "27": "C", "28": "C", "29": "C", "30": "C",
    "31": "C", "32": "C", "33": "C",
    "35": "D",
    "36": "E", "37": "E", "38": "E", "39": "E",
    "41": "F", "42": "F", "43": "F",
    "45": "G", "46": "G", "47": "G",
    "49": "H", "50": "H", "51": "H", "52": "H", "53": "H",
    "55": "I", "56": "I",
    "58": "J", "59": "J", "60": "J", "61": "J", "62": "J", "63": "J",
    "64": "K", "65": "K", "66": "K",
    "68": "L",
    "69": "M", "70": "M", "71": "M", "72": "M", "73": "M", "74": "M", "75": "M",
    "77": "N", "78": "N", "79": "N", "80": "N", "81": "N", "82": "N",
    "84": "O",
    "85": "P",
    "86": "Q", "87": "Q", "88": "Q",
    "90": "R", "91": "R", "92": "R", "93": "R",
    "94": "S", "95": "S", "96": "S",
    "97": "T", "98": "T",
    "99": "U",
}

# Detailed NAF codes: code → French label
NAF_CODES: dict[str, str] = {
    # ── A — Agriculture, sylviculture et peche ──
    "01.11Z": "Culture de cereales (sf riz), legumineuses, graines oleagineuses",
    "01.12Z": "Culture du riz",
    "01.13Z": "Culture de legumes, de melons, de racines et de tubercules",
    "01.14Z": "Culture de la canne a sucre",
    "01.15Z": "Culture du tabac",
    "01.16Z": "Culture de plantes a fibres",
    "01.19Z": "Autres cultures non permanentes",
    "01.21Z": "Culture de la vigne",
    "01.22Z": "Culture de fruits tropicaux et subtropicaux",
    "01.23Z": "Culture d'agrumes",
    "01.24Z": "Culture de fruits a pepins et a noyau",
    "01.25Z": "Culture d'autres fruits d'arbres ou d'arbustes et de fruits a coque",
    "01.26Z": "Culture de fruits oleagineux",
    "01.27Z": "Culture de plantes a boissons",
    "01.28Z": "Culture de plantes a epices, aromatiques, medicinales et pharmaceutiques",
    "01.29Z": "Autres cultures permanentes",
    "01.30Z": "Reproduction de plantes",
    "01.41Z": "Elevage de vaches laitieres",
    "01.42Z": "Elevage d'autres bovins et de buffles",
    "01.43Z": "Elevage de chevaux et d'autres equides",
    "01.44Z": "Elevage de chameaux et d'autres camelides",
    "01.45Z": "Elevage d'ovins et de caprins",
    "01.46Z": "Elevage de porcins",
    "01.47Z": "Elevage de volailles",
    "01.49Z": "Elevage d'autres animaux",
    "01.50Z": "Culture et elevage associes",
    "01.61Z": "Activites de soutien aux cultures",
    "01.62Z": "Activites de soutien a la production animale",
    "01.63Z": "Traitement primaire des recoltes",
    "01.64Z": "Traitement des semences",
    "01.70Z": "Chasse, piegeage et services annexes",
    "02.10Z": "Sylviculture et autres activites forestieres",
    "02.20Z": "Exploitation forestiere",
    "02.30Z": "Recolte de produits forestiers non ligneux poussant a l'etat sauvage",
    "02.40Z": "Services de soutien a l'exploitation forestiere",
    "03.11Z": "Peche en mer",
    "03.12Z": "Peche en eau douce",
    "03.21Z": "Aquaculture en mer",
    "03.22Z": "Aquaculture en eau douce",
    # ── C — Industrie manufacturiere (alimentaire) ──
    "10.11Z": "Transformation et conservation de la viande de boucherie",
    "10.12Z": "Transformation et conservation de la viande de volaille",
    "10.13A": "Preparation industrielle de produits a base de viande",
    "10.13B": "Charcuterie",
    "10.20Z": "Transformation et conservation de poisson, de crustaces et de mollusques",
    "10.31Z": "Transformation et conservation de pommes de terre",
    "10.32Z": "Preparation de jus de fruits et legumes",
    "10.39A": "Autre transformation et conservation de legumes",
    "10.39B": "Transformation et conservation de fruits",
    "10.41A": "Fabrication d'huiles et graisses brutes",
    "10.41B": "Fabrication d'huiles et graisses raffinees",
    "10.42Z": "Fabrication de margarine et graisses comestibles similaires",
    "10.51A": "Fabrication de lait liquide et de produits frais",
    "10.51B": "Fabrication de beurre",
    "10.51C": "Fabrication de fromage",
    "10.51D": "Fabrication d'autres produits laitiers",
    "10.52Z": "Fabrication de glaces et sorbets",
    "10.61A": "Meunerie",
    "10.61B": "Autres activites du travail des grains",
    "10.71A": "Fabrication industrielle de pain et de patisserie fraiche",
    "10.71B": "Cuisson de produits de boulangerie",
    "10.71C": "Boulangerie et boulangerie-patisserie",
    "10.71D": "Patisserie",
    "10.72Z": "Fabrication de biscuits, biscottes et patisseries de conservation",
    "10.73Z": "Fabrication de pates alimentaires",
    "10.81Z": "Fabrication de sucre",
    "10.82Z": "Fabrication de cacao, chocolat et de produits de confiserie",
    "10.83Z": "Transformation du the et du cafe",
    "10.84Z": "Fabrication de condiments et assaisonnements",
    "10.85Z": "Fabrication de plats prepares",
    "10.86Z": "Fabrication d'aliments homogeneises et dietetiques",
    "10.89Z": "Fabrication d'autres produits alimentaires n.c.a.",
    "10.91Z": "Fabrication d'aliments pour animaux de ferme",
    "10.92Z": "Fabrication d'aliments pour animaux de compagnie",
    "11.01Z": "Production de boissons alcooliques distillees",
    "11.02A": "Fabrication de vins effervescents",
    "11.02B": "Vinification",
    "11.03Z": "Fabrication de cidre et de vins de fruits",
    "11.04Z": "Production d'autres boissons fermentees non distillees",
    "11.05Z": "Fabrication de biere",
    "11.06Z": "Fabrication de malt",
    "11.07A": "Industrie des eaux de table",
    "11.07B": "Production de boissons rafraichissantes",
    # ── F — Construction ──
    "41.10A": "Developpement de projets immobiliers",
    "41.10B": "Developpement de projets fonctionnels",
    "41.20A": "Construction de maisons individuelles",
    "41.20B": "Construction d'autres batiments",
    "42.11Z": "Construction de routes et autoroutes",
    "42.12Z": "Construction de voies ferrees de surface et souterraines",
    "42.13A": "Construction d'ouvrages d'art",
    "42.13B": "Construction et entretien de tunnels",
    "42.21Z": "Construction de reseaux pour fluides",
    "42.22Z": "Construction de reseaux electriques et de telecommunications",
    "42.91Z": "Construction d'ouvrages maritimes et fluviaux",
    "42.99Z": "Construction d'autres ouvrages de genie civil n.c.a.",
    "43.11Z": "Travaux de demolition",
    "43.12A": "Travaux de terrassement courants et travaux preparatoires",
    "43.12B": "Travaux de terrassement specialises ou de grande masse",
    "43.13Z": "Forages et sondages",
    "43.21A": "Travaux d'installation electrique dans tous locaux",
    "43.21B": "Travaux d'installation electrique sur la voie publique",
    "43.22A": "Travaux d'installation d'eau et de gaz en tous locaux",
    "43.22B": "Travaux d'installation d'equipements thermiques et de climatisation",
    "43.29A": "Travaux d'isolation",
    "43.29B": "Autres travaux d'installation n.c.a.",
    "43.31Z": "Travaux de platrerie",
    "43.32A": "Travaux de menuiserie bois et PVC",
    "43.32B": "Travaux de menuiserie metallique et serrurerie",
    "43.32C": "Agencement de lieux de vente",
    "43.33Z": "Travaux de revetement des sols et des murs",
    "43.34Z": "Travaux de peinture et vitrerie",
    "43.39Z": "Autres travaux de finition",
    "43.91A": "Travaux de charpente",
    "43.91B": "Travaux de couverture par elements",
    "43.99A": "Travaux d'etancheification",
    "43.99B": "Travaux de montage de structures metalliques",
    "43.99C": "Travaux de maconnerie generale et target gros oeuvre de batiment",
    "43.99D": "Autres travaux specialises de construction",
    "43.99E": "Location avec operateur de materiel de construction",
    # ── G — Commerce ──
    "45.11Z": "Commerce de voitures et de vehicules automobiles legers",
    "45.19Z": "Commerce d'autres vehicules automobiles",
    "45.20A": "Entretien et reparation de vehicules automobiles legers",
    "45.20B": "Entretien et reparation d'autres vehicules automobiles",
    "45.32Z": "Commerce de detail d'equipements automobiles",
    "45.40Z": "Commerce et reparation de motocycles",
    "46.11Z": "Intermediaires du commerce en matieres premieres agricoles, animaux vivants",
    "46.17A": "Centrales d'achat alimentaires",
    "46.17B": "Autres intermediaires du commerce en denrees, boissons et tabac",
    "46.21Z": "Commerce de gros de cereales, de tabac non manufacture, de semences et d'aliments pour le betail",
    "46.31Z": "Commerce de gros de fruits et legumes",
    "46.32Z": "Commerce de gros de viandes et de produits a base de viande",
    "46.34Z": "Commerce de gros de boissons",
    "46.39A": "Commerce de gros de produits surgeles",
    "46.39B": "Commerce de gros alimentaire specialise divers",
    "46.49Z": "Commerce de gros d'autres biens domestiques",
    "46.69A": "Commerce de gros de materiel agricole",
    "46.69B": "Commerce de gros de fournitures et equipements industriels divers",
    "46.69C": "Commerce de gros de fournitures et equipements divers pour le commerce et les services",
    "46.71Z": "Commerce de gros de combustibles et de produits annexes",
    "46.73A": "Commerce de gros de bois et de materiaux de construction",
    "46.90Z": "Commerce de gros non specialise",
    "47.11A": "Commerce de detail de produits surgeles",
    "47.11B": "Commerce d'alimentation generale",
    "47.11C": "Superettes",
    "47.11D": "Supermarches",
    "47.11E": "Magasins multi-commerces",
    "47.11F": "Hypermarches",
    "47.21Z": "Commerce de detail de fruits et legumes en magasin specialise",
    "47.22Z": "Commerce de detail de viandes et de produits a base de viande en magasin specialise",
    "47.23Z": "Commerce de detail de poissons, crustaces et mollusques en magasin specialise",
    "47.24Z": "Commerce de detail de pain, patisserie et confiserie en magasin specialise",
    "47.25Z": "Commerce de detail de boissons en magasin specialise",
    "47.26Z": "Commerce de detail de produits a base de tabac en magasin specialise",
    "47.52A": "Commerce de detail de quincaillerie, peintures et verres en petites surfaces",
    "47.52B": "Commerce de detail de quincaillerie, peintures et verres en grandes surfaces",
    "47.61Z": "Commerce de detail de livres en magasin specialise",
    "47.71Z": "Commerce de detail d'habillement en magasin specialise",
    "47.73Z": "Commerce de detail de produits pharmaceutiques en magasin specialise",
    "47.74Z": "Commerce de detail d'articles medicaux et orthopediques en magasin specialise",
    "47.76Z": "Commerce de detail de fleurs, plantes, graines, engrais, animaux de compagnie",
    "47.78C": "Autres commerces de detail specialises divers",
    "47.91A": "Vente a distance sur catalogue general",
    "47.91B": "Vente a distance sur catalogue specialise",
    "47.99A": "Vente a domicile",
    "47.99B": "Vente par automates et autres commerces de detail hors magasin n.c.a.",
    # ── H — Transports ──
    "49.10Z": "Transport ferroviaire interurbain de voyageurs",
    "49.20Z": "Transports ferroviaires de fret",
    "49.31Z": "Transports urbains et suburbains de voyageurs",
    "49.32Z": "Transports de voyageurs par taxis",
    "49.39A": "Transports routiers reguliers de voyageurs",
    "49.39B": "Autres transports routiers de voyageurs",
    "49.39C": "Telepheriques et remontees mecaniques",
    "49.41A": "Transports routiers de fret interurbains",
    "49.41B": "Transports routiers de fret de proximite",
    "49.41C": "Location de camions avec chauffeur",
    "49.42Z": "Services de demenagement",
    "49.50Z": "Transports par conduites",
    "50.10Z": "Transports maritimes et cotiers de passagers",
    "50.20Z": "Transports maritimes et cotiers de fret",
    "51.10Z": "Transports aeriens de passagers",
    "52.10A": "Entreposage et stockage frigorifique",
    "52.10B": "Entreposage et stockage non frigorifique",
    "52.21Z": "Services auxiliaires des transports terrestres",
    "52.29A": "Messagerie, fret express",
    "52.29B": "Affretement et organisation des transports",
    "53.10Z": "Activites de poste dans le cadre d'une obligation de service universel",
    "53.20Z": "Autres activites de poste et de courrier",
    # ── I — Hebergement et restauration ──
    "55.10Z": "Hotels et hebergement similaire",
    "55.20Z": "Hebergement touristique et autre hebergement de courte duree",
    "55.30Z": "Terrains de camping et parcs pour caravanes ou vehicules de loisirs",
    "55.90Z": "Autres hebergements",
    "56.10A": "Restauration traditionnelle",
    "56.10B": "Cafeterias et autres libres-services",
    "56.10C": "Restauration de type rapide",
    "56.21Z": "Services des traiteurs",
    "56.29A": "Restauration collective sous contrat",
    "56.29B": "Autres services de restauration n.c.a.",
    "56.30Z": "Debits de boissons",
    # ── J — Information et communication ──
    "58.11Z": "Edition de livres",
    "58.12Z": "Edition de repertoires et de fichiers d'adresses",
    "58.13Z": "Edition de journaux",
    "58.14Z": "Edition de revues et periodiques",
    "58.21Z": "Edition de jeux electroniques",
    "58.29A": "Edition de logiciels systeme et de reseau",
    "58.29B": "Edition de logiciels outils de developpement et de langages",
    "58.29C": "Edition de logiciels applicatifs",
    "59.11A": "Production de films et de programmes pour la television",
    "59.11B": "Production de films institutionnels et publicitaires",
    "59.11C": "Production de films pour le cinema",
    "59.12Z": "Post-production de films cinematographiques, de video et de programmes de television",
    "59.14Z": "Projection de films cinematographiques",
    "60.10Z": "Edition et diffusion de programmes radio",
    "60.20A": "Edition de chaines generalistes",
    "60.20B": "Edition de chaines thematiques",
    "61.10Z": "Telecommunications filaires",
    "61.20Z": "Telecommunications sans fil",
    "61.30Z": "Telecommunications par satellite",
    "61.90Z": "Autres activites de telecommunication",
    "62.01Z": "Programmation informatique",
    "62.02A": "Conseil en systemes et logiciels informatiques",
    "62.02B": "Tierce maintenance de systemes et d'applications informatiques",
    "62.03Z": "Gestion d'installations informatiques",
    "62.09Z": "Autres activites informatiques",
    "63.11Z": "Traitement de donnees, hebergement et activites connexes",
    "63.12Z": "Portails Internet",
    "63.91Z": "Activites des agences de presse",
    "63.99Z": "Autres services d'information n.c.a.",
    # ── K — Activites financieres ──
    "64.11Z": "Activites de banque centrale",
    "64.19Z": "Autres intermediations monetaires",
    "64.20Z": "Activites des societes holding",
    "64.30Z": "Fonds de placement et entites financieres similaires",
    "64.91Z": "Credit-bail",
    "64.92Z": "Autre distribution de credit",
    "64.99Z": "Autres intermediations financieres n.c.a.",
    "65.11Z": "Assurance vie",
    "65.12Z": "Autres assurances",
    "65.20Z": "Reassurance",
    "65.30Z": "Caisses de retraite",
    "66.11Z": "Administration de marches financiers",
    "66.12Z": "Courtage de valeurs mobilieres et de marchandises",
    "66.19A": "Activites des agents et courtiers d'assurances",
    "66.19B": "Autres activites auxiliaires d'assurance et de caisses de retraite",
    "66.21Z": "Evaluation des risques et dommages",
    "66.22Z": "Activites des agents et courtiers d'assurances",
    "66.30Z": "Gestion de fonds",
    # ── L — Activites immobilieres ──
    "68.10Z": "Activites des marchands de biens immobiliers",
    "68.20A": "Location de logements",
    "68.20B": "Location de terrains et d'autres biens immobiliers",
    "68.31Z": "Agences immobilieres",
    "68.32A": "Administration d'immeubles et autres biens immobiliers",
    "68.32B": "Supports juridiques de gestion de patrimoine immobilier",
    # ── M — Activites specialisees, scientifiques et techniques ──
    "69.10Z": "Activites juridiques",
    "69.20Z": "Activites comptables",
    "70.10Z": "Activites des sieges sociaux",
    "70.21Z": "Conseil en relations publiques et communication",
    "70.22Z": "Conseil pour les affaires et autres conseils de gestion",
    "71.11Z": "Activites d'architecture",
    "71.12A": "Activite des geometres",
    "71.12B": "Ingenierie, etudes techniques",
    "71.20A": "Controle technique automobile",
    "71.20B": "Analyses, essais et inspections techniques",
    "72.11Z": "Recherche-developpement en biotechnologie",
    "72.19Z": "Recherche-developpement en autres sciences physiques et naturelles",
    "72.20Z": "Recherche-developpement en sciences humaines et sociales",
    "73.11Z": "Activites des agences de publicite",
    "73.12Z": "Regie publicitaire de medias",
    "73.20Z": "Etudes de marche et sondages",
    "74.10Z": "Activites specialisees de design",
    "74.20Z": "Activites photographiques",
    "74.30Z": "Traduction et interpretation",
    "74.90A": "Activite des economistes de la construction",
    "74.90B": "Activites specialisees, scientifiques et techniques diverses",
    "75.00Z": "Activites veterinaires",
    # ── N — Activites de services administratifs ──
    "77.11A": "Location de courte duree de voitures et de vehicules automobiles legers",
    "77.11B": "Location de longue duree de voitures et de vehicules automobiles legers",
    "78.10Z": "Activites des agences de placement de main-d'oeuvre",
    "78.20Z": "Activites des agences de travail temporaire",
    "79.11Z": "Activites des agences de voyage",
    "79.12Z": "Activites des voyagistes",
    "80.10Z": "Activites de securite privee",
    "81.10Z": "Activites combinees de soutien lie aux batiments",
    "81.21Z": "Nettoyage courant des batiments",
    "81.22Z": "Autres activites de nettoyage des batiments et nettoyage industriel",
    "81.29A": "Desinfection, desinsectisation, deratisation",
    "81.29B": "Autres activites de nettoyage n.c.a.",
    "81.30Z": "Services d'amenagement paysager",
    "82.11Z": "Services administratifs combines de bureau",
    "82.19Z": "Photocopie, preparation de documents et autres activites specialisees de soutien de bureau",
    "82.20Z": "Activites de centres d'appels",
    "82.30Z": "Organisation de foires, salons professionnels et congres",
    "82.91Z": "Activites des agences de recouvrement de factures et des societes d'information financiere",
    "82.92Z": "Activites de conditionnement",
    "82.99Z": "Autres activites de soutien aux entreprises n.c.a.",
    # ── P — Enseignement ──
    "85.10Z": "Enseignement pre-primaire",
    "85.20Z": "Enseignement primaire",
    "85.31Z": "Enseignement secondaire general",
    "85.32Z": "Enseignement secondaire technique ou professionnel",
    "85.41Z": "Enseignement post-secondaire non superieur",
    "85.42Z": "Enseignement superieur",
    "85.51Z": "Enseignement de disciplines sportives et d'activites de loisirs",
    "85.52Z": "Enseignement culturel",
    "85.53Z": "Enseignement de la conduite",
    "85.59A": "Formation continue d'adultes",
    "85.59B": "Autres enseignements",
    "85.60Z": "Activites de soutien a l'enseignement",
    # ── Q — Sante humaine et action sociale ──
    "86.10Z": "Activites hospitalieres",
    "86.21Z": "Activite des medecins generalistes",
    "86.22A": "Activites de radiodiagnostic et de radiotherapie",
    "86.22B": "Activites chirurgicales",
    "86.22C": "Autres activites des medecins specialistes",
    "86.23Z": "Pratique dentaire",
    "86.90A": "Ambulances",
    "86.90B": "Laboratoires d'analyses medicales",
    "86.90C": "Centres de collecte et banques d'organes",
    "86.90D": "Activites des infirmiers et des sages-femmes",
    "86.90E": "Activites des professionnels de la reeducation, de l'appareillage et des pedicures-podologues",
    "86.90F": "Activites de sante humaine non classees ailleurs",
    "87.10A": "Hebergement medicalise pour personnes agees",
    "87.10B": "Hebergement medicalise pour enfants handicapes",
    "87.10C": "Hebergement medicalise pour adultes handicapes et autre hebergement medicalise",
    "87.20Z": "Hebergement social pour handicapes mentaux, malades mentaux et toxicomanes",
    "87.30A": "Hebergement social pour personnes agees",
    "87.30B": "Hebergement social pour handicapes physiques",
    "87.90A": "Hebergement social pour enfants en difficultes",
    "87.90B": "Hebergement social pour adultes et familles en difficultes et autre hebergement social",
    "88.10A": "Aide a domicile",
    "88.10B": "Accueil ou accompagnement sans hebergement d'adultes handicapes ou de personnes agees",
    "88.10C": "Aide par le travail",
    "88.91A": "Accueil de jeunes enfants",
    "88.91B": "Accueil ou accompagnement sans hebergement d'enfants handicapes",
    "88.99A": "Autre accueil ou accompagnement sans hebergement d'enfants et d'adolescents",
    "88.99B": "Action sociale sans hebergement n.c.a.",
    # ── R — Arts, spectacles ──
    "90.01Z": "Arts du spectacle vivant",
    "90.02Z": "Activites de soutien au spectacle vivant",
    "90.03A": "Creation artistique relevant des arts plastiques",
    "90.03B": "Autre creation artistique",
    "90.04Z": "Gestion de salles de spectacles",
    "91.01Z": "Gestion des bibliotheques et des archives",
    "91.02Z": "Gestion des musees",
    "91.03Z": "Gestion des sites et monuments historiques et des attractions touristiques similaires",
    "91.04Z": "Gestion des jardins botaniques et zoologiques et des reserves naturelles",
    "92.00Z": "Organisation de jeux de hasard et d'argent",
    "93.11Z": "Gestion d'installations sportives",
    "93.12Z": "Activites de clubs de sports",
    "93.13Z": "Activites des centres de culture physique",
    "93.19Z": "Autres activites liees au sport",
    "93.21Z": "Activites des parcs d'attractions et parcs a themes",
    "93.29Z": "Autres activites recreatives et de loisirs",
    # ── S — Autres activites de services ──
    "94.11Z": "Activites des organisations patronales et consulaires",
    "94.12Z": "Activites des organisations professionnelles",
    "94.20Z": "Activites des syndicats de salaries",
    "94.91Z": "Activites des organisations religieuses",
    "94.92Z": "Activites des organisations politiques",
    "94.99Z": "Autres organisations fonctionnant par adhesion volontaire",
    "95.11Z": "Reparation d'ordinateurs et d'equipements peripheriques",
    "95.12Z": "Reparation d'equipements de communication",
    "95.21Z": "Reparation de produits electroniques grand public",
    "95.22Z": "Reparation d'appareils electromenagers et d'equipements pour la maison et le jardin",
    "95.23Z": "Reparation de chaussures et d'articles en cuir",
    "95.24Z": "Reparation de meubles et d'equipements du foyer",
    "95.25Z": "Reparation d'articles d'horlogerie et de bijouterie",
    "95.29Z": "Reparation d'autres biens personnels et domestiques",
    "96.01A": "Blanchisserie-teinturerie de gros",
    "96.01B": "Blanchisserie-teinturerie de detail",
    "96.02A": "Coiffure",
    "96.02B": "Soins de beaute",
    "96.03Z": "Services funeraires",
    "96.04Z": "Entretien corporel",
    "96.09Z": "Autres services personnels n.c.a.",
}


def get_section_for_code(naf_code: str) -> str | None:
    """Return section letter for a NAF code (e.g. '62.01Z' → 'J')."""
    division = naf_code[:2]
    return NAF_DIVISION_TO_SECTION.get(division)


def get_naf_label(naf_code: str) -> str | None:
    """Return French label for a specific NAF code."""
    return NAF_CODES.get(naf_code)
